<?php

use Carbon\Carbon;
use Illuminate\Database\Seeder;

class MenusHasRolesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('menus_has_roles')->insert([
            [
                'menu_id' => 1,
                'rol_id' => 1,
                'owner_user_id' => 1,
                'owner_user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'menu_id' => 1,
                'rol_id' => 2,
                'owner_user_id' => 1,
                'owner_user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'menu_id' => 1,
                'rol_id' => 3,
                'owner_user_id' => 1,
                'owner_user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'menu_id' => 1,
                'rol_id' => 5,
                'owner_user_id' => 1,
                'owner_user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'menu_id' => 2,
                'rol_id' => 1,
                'owner_user_id' => 1,
                'owner_user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'menu_id' => 2,
                'rol_id' => 2,
                'owner_user_id' => 1,
                'owner_user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'menu_id' => 2,
                'rol_id' => 3,
                'owner_user_id' => 1,
                'owner_user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'menu_id' => 2,
                'rol_id' => 5,
                'owner_user_id' => 1,
                'owner_user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'menu_id' => 3,
                'rol_id' => 1,
                'owner_user_id' => 1,
                'owner_user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'menu_id' => 3,
                'rol_id' => 2,
                'owner_user_id' => 1,
                'owner_user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'menu_id' => 3,
                'rol_id' => 3,
                'owner_user_id' => 1,
                'owner_user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'menu_id' => 3,
                'rol_id' => 5,
                'owner_user_id' => 1,
                'owner_user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'menu_id' => 4,
                'rol_id' => 1,
                'owner_user_id' => 1,
                'owner_user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'menu_id' => 4,
                'rol_id' => 2,
                'owner_user_id' => 1,
                'owner_user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'menu_id' => 4,
                'rol_id' => 3,
                'owner_user_id' => 1,
                'owner_user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'menu_id' => 4,
                'rol_id' => 5,
                'owner_user_id' => 1,
                'owner_user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'menu_id' => 5,
                'rol_id' => 1,
                'owner_user_id' => 1,
                'owner_user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'menu_id' => 5,
                'rol_id' => 2,
                'owner_user_id' => 1,
                'owner_user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'menu_id' => 5,
                'rol_id' => 3,
                'owner_user_id' => 1,
                'owner_user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'menu_id' => 5,
                'rol_id' => 5,
                'owner_user_id' => 1,
                'owner_user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'menu_id' => 6,
                'rol_id' => 1,
                'owner_user_id' => 1,
                'owner_user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'menu_id' => 6,
                'rol_id' => 2,
                'owner_user_id' => 1,
                'owner_user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'menu_id' => 6,
                'rol_id' => 3,
                'owner_user_id' => 1,
                'owner_user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'menu_id' => 7,
                'rol_id' => 1,
                'owner_user_id' => 1,
                'owner_user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'menu_id' => 7,
                'rol_id' => 2,
                'owner_user_id' => 1,
                'owner_user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'menu_id' => 8,
                'rol_id' => 1,
                'owner_user_id' => 1,
                'owner_user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'menu_id' => 8,
                'rol_id' => 2,
                'owner_user_id' => 1,
                'owner_user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'menu_id' => 9,
                'rol_id' => 1,
                'owner_user_id' => 1,
                'owner_user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'menu_id' => 9,
                'rol_id' => 2,
                'owner_user_id' => 1,
                'owner_user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'menu_id' => 9,
                'rol_id' => 3,
                'owner_user_id' => 1,
                'owner_user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'menu_id' => 9,
                'rol_id' => 5,
                'owner_user_id' => 1,
                'owner_user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'menu_id' => 10,
                'rol_id' => 1,
                'owner_user_id' => 1,
                'owner_user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'menu_id' => 11,
                'rol_id' => 1,
                'owner_user_id' => 1,
                'owner_user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'menu_id' => 11,
                'rol_id' => 2,
                'owner_user_id' => 1,
                'owner_user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ]
        ]);
    }
}
